version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-rpg
    ports:
      - "8080:8080" # Port pour accéder à Jenkins
      - "50000:50000" # Port pour les agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
